// Nama : Talitha Aurelia Shakira
// NIM  : 11200930000023
// Kelas : 2A

package GUI;

import java.awt.CardLayout;

/**
 *
 * @author LENOVO
 */
public class AplikasiPenampilGambar extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiPenampilGambar
     */
    public AplikasiPenampilGambar() {
        initComponents();
         initLevel0 ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ButtonLayout = new javax.swing.JPanel();
        BtnLondon = new javax.swing.JButton();
        BtnIndonesia = new javax.swing.JButton();
        BtnItalia = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();
        ImageLayout = new javax.swing.JPanel();
        TxtLondon = new javax.swing.JLabel();
        TxtIndonesia = new javax.swing.JLabel();
        TxtItalia = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonLayout.setBackground(new java.awt.Color(51, 0, 51));

        BtnLondon.setBackground(new java.awt.Color(255, 153, 102));
        BtnLondon.setText("London");
        BtnLondon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLondonActionPerformed(evt);
            }
        });
        ButtonLayout.add(BtnLondon);

        BtnIndonesia.setBackground(new java.awt.Color(255, 153, 102));
        BtnIndonesia.setText("Indonesia");
        BtnIndonesia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIndonesiaActionPerformed(evt);
            }
        });
        ButtonLayout.add(BtnIndonesia);

        BtnItalia.setBackground(new java.awt.Color(255, 153, 102));
        BtnItalia.setText("Italia");
        BtnItalia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnItaliaActionPerformed(evt);
            }
        });
        ButtonLayout.add(BtnItalia);

        BtnExit.setBackground(new java.awt.Color(255, 153, 102));
        BtnExit.setText("Exit");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        ButtonLayout.add(BtnExit);

        getContentPane().add(ButtonLayout, java.awt.BorderLayout.PAGE_START);

        ImageLayout.setLayout(new java.awt.CardLayout());

        TxtLondon.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Pictures\\Saved Pictures\\london fix fix.jpg")); // NOI18N
        ImageLayout.add(TxtLondon, "0");

        TxtIndonesia.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Pictures\\Saved Pictures\\Indonesia.jpg")); // NOI18N
        ImageLayout.add(TxtIndonesia, "1");

        TxtItalia.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Pictures\\Saved Pictures\\italia fix.jpg")); // NOI18N
        ImageLayout.add(TxtItalia, "2");

        getContentPane().add(ImageLayout, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLondonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLondonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(ImageLayout.getLayout());
        cl.show (ImageLayout, "0");
    }//GEN-LAST:event_BtnLondonActionPerformed

    private void BtnIndonesiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIndonesiaActionPerformed
        // TODO add your handling code here:
         CardLayout cl = (CardLayout)(ImageLayout.getLayout());
          cl.show (ImageLayout, "1");
    }//GEN-LAST:event_BtnIndonesiaActionPerformed

    private void BtnItaliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnItaliaActionPerformed
        // TODO add your handling code here:
         CardLayout cl = (CardLayout)(ImageLayout.getLayout());
          cl.show (ImageLayout, "2");    
    }//GEN-LAST:event_BtnItaliaActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BtnExitActionPerformed
     private void initLevel0 (){
        setLocationRelativeTo (null);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPenampilGambar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnIndonesia;
    private javax.swing.JButton BtnItalia;
    private javax.swing.JButton BtnLondon;
    private javax.swing.JPanel ButtonLayout;
    private javax.swing.JPanel ImageLayout;
    private javax.swing.JLabel TxtIndonesia;
    private javax.swing.JLabel TxtItalia;
    private javax.swing.JLabel TxtLondon;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
